service: shipping
provider:
  name: aws
  runtime: java11
  timeout: 60
  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DeleteNetworkInterface'
      Resource: "*"
package:
  artifact: target/shipping-original.jar
functions:
  shipping:
    environment:
      RABBIT_MQ_URI: ${opt:uri}
      RABBIT_MQ_USERNAME: ${opt:username}
      RABBIT_MQ_PASSWORD: ${opt:password}
    handler: works.weave.socks.shipping.StreamLambdaAsyncHandler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    provisionedConcurrency: 1